import{a as c,b as u,i as d}from"./assets/vendor-715407fd.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const a={inputElements:document.querySelectorAll("input"),inputEmail:document.querySelector(".form-email"),inputComment:document.querySelector(".form-comment"),buttonElement:document.querySelector(".form-button")},f=30;a.inputEmail.value.trim();a.inputComment.value.trim();const p=(o,r)=>{o.value.length>r&&(o.value=o.value.slice(0,r-3)+"...")};a.inputElements.forEach(o=>{o.addEventListener("input",()=>p(o,f))});const l=(o,r)=>{const n=JSON.stringify(r);localStorage.setItem(o,n)},m=o=>{const r=localStorage.getItem(o);try{return JSON.parse(r)}catch{return r}};async function v(o,r){const n="https://portfolio-js.b.goit.study/api",i={email:o.value,comment:r.value,headers:{"Content-Type":"application/json"}};try{const e=await c.post(n,i);if(e.ok)return u.create(`
    <div class="modal">
    <h2 class="modal-title">Thank you for your interest in cooperation!</h2>
        <p class="modal-text">
        The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.
        </p>
    </div>
`).show(),form.reset(),e}catch{d.show({message:"An error occurred while posting your data. Please, try again later.",position:"bottomCenter",backgroundColor:"#ED3B44",messageColor:"#ffffff",theme:"dark",maxWidth:"350px"}),formElement.addEventListener("input",t=>{const s={email:a.inputEmail.value.trim(),comment:a.inputComment.value.trim()};l("email",s.email.value),l("comment",s.comment.value)}),form.addEventListener("submit",t=>{t.preventDefault(),post.email=form.elements.email.value,post.comment=form.elements.message.value,console.log(post),form.reset(),localStorage.removeItem("email"),localStorage.removeItem("comment")}),document.addEventListener("DOMContentLoaded",()=>{m("email"),m("comment"),form.elements.email.value=post.email,form.elements.comment.value=post.comment})}}a.buttonElement.addEventListener("submit",v);
//# sourceMappingURL=commonHelpers.js.map
